import { cva } from 'class-variance-authority'

export const inputStyles = cva(
  [
    'w-full',
    'appearance-none',
    'shadow-xs',
    'rounded-md',
    'border',
    'bg-background',
    'px-3',
    'py-2',
    'pointer-coarse:max-lg:px-3.5',
    'text-sm',
    'pointer-coarse:max-lg:text-base',
    'file:border-0',
    'file:bg-transparent',
    'file:font-medium',
    'focus-visible:shadow-none',
    'focus-visible:outline-offset-0',
    'focus-visible:outline-1',
    'not-in-[.ck-invalid]:focus-visible:outline-primary',
    'in-[.ck-invalid]:border-destructive',
    'in-[.ck-invalid]:text-destructive',
    'in-[.ck-invalid]:placeholder:text-destructive/70',
    '[&:is(select)]:bg-select-chevron-down',
    '[&:is(select)]:!bg-[right_.5rem_center]',
    '[&:is(select)]:bg-no-repeat',
    '[&:not(textarea)]:h-10',
    '[&:not(textarea)]:pointer-coarse:max-lg:h-11',
    '[&[readonly]]:bg-muted/50',
    'disabled:bg-muted',
    'disabled:shadow-none',
  ],
  {
    variants: {
      padStart: { true: 'ps-9 pointer-coarse:max-lg:ps-9.5' },
      padEnd: { true: 'pe-9 pointer-coarse:max-lg:pe-9.5' },
    },
  },
)
