name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lint_commits:
    name: Lint commit messages
    runs-on: ubuntu-latest
    env:
      BASE_REF: ${{ github.event.pull_request.base.ref }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      HEAD_REF: ${{ github.event.pull_request.head.ref }}
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      PR_TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm i -g commitlint @commitlint/config-angular

      - name: Lint
        run: bash .github/workflows/scripts/lint-commit-names.sh

  lint_code:
    name: Lint code
    needs: lint_commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
